CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS intermediate;
CREATE SCHEMA IF NOT EXISTS marts;

GRANT ALL PRIVILEGES ON SCHEMA raw TO hospital_user;
GRANT ALL PRIVILEGES ON SCHEMA staging TO hospital_user;
GRANT ALL PRIVILEGES ON SCHEMA intermediate TO hospital_user;
GRANT ALL PRIVILEGES ON SCHEMA marts TO hospital_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL PRIVILEGES ON TABLES TO hospital_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT ALL PRIVILEGES ON TABLES TO hospital_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA intermediate GRANT ALL PRIVILEGES ON TABLES TO hospital_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA marts GRANT ALL PRIVILEGES ON TABLES TO hospital_user;

CREATE TABLE IF NOT EXISTS raw.hospital_pipeline_runs (
    run_id BIGSERIAL PRIMARY KEY,
    pipeline_stage TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    details JSONB DEFAULT '{}'::JSONB
);

GRANT ALL PRIVILEGES ON TABLE raw.hospital_pipeline_runs TO hospital_user;
GRANT USAGE, SELECT ON SEQUENCE raw.hospital_pipeline_runs_run_id_seq TO hospital_user;
