name: hospital_analytics
version: '1.0.0'
config-version: 2
profile: hospital_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  hospital_analytics:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  hospital_analytics:
    +schema: staging
    +quote_columns: false
